title: neuro.FH
email: fharell@neurofh.com
description: Neuroscience, medicine, research, and the things I'm figuring out along the way.

baseurl: ""
url: "https://neurofh.com"

github_username: neurofh

remote_theme: chrisrhymes/bulma-clean-theme@v0.14.0

plugins:
  - jekyll-remote-theme